### ISSUE TITLE
bug: don't have enough information to build a robust unique id for the TextField component. 

### ISSUE THREAD

**Issue by beiweiqiang** [LoicMahieu/material-ui-color-picker#1]
I think it should add more properties to the component, otherwise it will display the bug:
Warning: We don't have enough information to build a robust unique id for the TextField component. Please provide an id or a name.
I fixed the bug by adding some properties.
<ColorPicker
  name="colorPicker"
  hintText="pick your color"
  floatingLabelText="pick your color"
  id="colorPicker"
  defaultValue="#000"
  onChange={color => console.log(color)}
/>

**Comment by LoicMahieu** [comment]
I suppose you talk about the sample in the README ? Yep it could, I didn't test it ;) Adding a `name` is enough I think.
