### ISSUE TITLE
how to set value of the colorpicker later on state update?

### ISSUE THREAD

**Issue by abhisheksdm** [LoicMahieu/material-ui-color-picker#18]
Hello,
I am unable to set value prop for colorpicker, i am only able to set defaultValue prop, so i am unable to change the value of the field later with change in props.
kindly help me

**Comment by LoicMahieu** [comment]
As much for me, I was wrong. There is a state in the `ColorPicker` component. This issue will be fixed by #11

**Comment by LoicMahieu** [comment]
Fixed by https://github.com/LoicMahieu/material-ui-color-picker/pull/20
+ material-ui-color-picker@3.1.0
