### ISSUE TITLE
missing material-ui peerDependancy?

### ISSUE THREAD

**Issue by id0Sch** [LoicMahieu/material-ui-color-picker#2]
Hi,
just stumbled upon your package and im getting ready to use it,
couldn't help but notice that your'e missing a dependency for material-ui.
everything should work, but when someone who isn't using material-ui will try to install it - he will be able to , but the lib won't work.

for your consideration.
thanks,

**Comment by LoicMahieu** [comment]
Hi!
Indeed, thanks!
