### ISSUE TITLE
When I am changing the color from palette hex code is not getting updated the input field I am using functional component 

### ISSUE THREAD

**Issue by sumitintelligaia** [LoicMahieu/material-ui-color-picker#70]
const [colorPicker, setColorPicker] = useState('#fff');
    const handleColorPickerChange = (color) => {console.log(color)
        setColorPicker(color);
    }
  <ColorPicker name="color" value={colorPicker} onChange={color => handleColorPickerChange(color)}
                                />

**Comment by PavlyukVadim** [comment]
@sumitintelligaia just add such prop `InputProps={{ value }}`

**Comment by sumitintelligaia** [comment]
@PavlyukVadim Its giving me 
![image](https://user-images.githubusercontent.com/37867509/131620493-6c3084e6-881a-471d-b9a3-5f63640b33fd.png)
And I am using functional component.

**Comment by sergioguzman27** [comment]
> @PavlyukVadim Its giving me ![image](https://user-images.githubusercontent.com/37867509/131620493-6c3084e6-881a-471d-b9a3-5f63640b33fd.png) And I am using functional component.

You used a color prop but you should use value prop. For example:
```
<ColorPicker
       InputProps={{ zIndex: 0, value: valueColor }}
/>
```

**Comment by sumitintelligaia** [comment]
okay Thanks!
